### ISSUE TITLE
Error: No such file or directory

### ISSUE THREAD

**Issue by stabbornweb** [rcravens/kit#3]
After clone repo and run ./.code/bin/install.sh I am getting an error.

![image](https://github.com/user-attachments/assets/3655b3bb-0e13-49a6-95f1-cad7b706f6b2)

OS:
Windows 10, WSL 2 on Ubuntu 22.04.

**Comment by stabbornweb** [comment]
To fix this problem need a clone repo with this config for lines.

`git clone https://github.com/rcravens/kit.git  --config core.autocrlf=false infra`

Also, you can read more about this problem here.
https://github.com/flutter/website/issues/8615#issuecomment-1692692878

**Comment by rcravens** [comment]
Thank you @stabornweb! I've made a commit to fix this issue.
