### ISSUE TITLE
Problem: sed: -e expression #1, char 1: unknown command: `.'

### ISSUE THREAD

**Issue by YevheniiVolosiuk** [rcravens/kit#4]
OS: Windows 10, WSL 2 on Ubuntu 22.04

Problem View:
![image](https://github.com/user-attachments/assets/a17355c6-650c-4449-b427-1c56637a2dc9)

**Comment by YevheniiVolosiuk** [comment]
To fix this problem need to make file changes
.code/bin/commands/deploy.sh
.code/bin/makes/registry.sh

from `sed -i. bak` to `sed -i.bak` after will work one 2 OS.

**Comment by rcravens** [comment]
Thank you @YevheniiVolosiuk !
